<?php


/**
 * @file 
 * 
 * Defines a text widget for content types that are used as simplenews newsletters.
 * This can only be used by newsletters that are sent as html mails and use a specified
 * field for their plaintext content. The widget consists of a textarea and an additional
 * 'process' button which allows a serverside conversion of the typed text into plaintext.
 * 
 * Notes
 * Don't use "Filtered text" with the plaintext field.
 * @todo try to avoid "filtered text".
 * 
 */

/**
 * Implements hook_field_widget_info().
 */
function simplenews_plaintext_field_widget_info() {
  
  return array(
    'plaintext_textarea' => array(
      'label' => t('Textarea for Plaintext (multiple rows)'),
      'field types' => array('text_long'),
      'settings' => array('rows' => 20),
    ),
  );
}

/*
 * Implements hook_field_create_instance().
 * 
 * Enables the display style 'email_plain' and sets the
 * display of the created field in 'email_plain' to hidden.
 */
function simplenews_plaintext_field_create_instance($instance) {
  
  if ($instance['widget']['type'] == 'plaintext_textarea') {
    $bundle_settings = array(
      'view_modes' => array(
        'email_plain' => array('custom_settings' => TRUE),
      ),
    );
    field_bundle_settings('node',  $instance['bundle'], $bundle_settings);
    
    $instance['display']['email_plain'] = array(
      'label' => 'hidden',
      'type' => 'hidden',
    );
    field_update_instance($instance);
  }
}

/**
 * Implements hook_field_widget_settings_form().
 */
function simplenews_plaintext_field_widget_settings_form($field, $instance) {
  
  $widget = $instance['widget'];
  $settings = $widget['settings'];

  $form['rows'] = array(
    '#type' => 'textfield',
    '#title' => t('Rows'),
    '#default_value' => $settings['rows'],
    '#required' => TRUE,
    '#element_validate' => array('element_validate_integer_positive'),
  );

  return $form;
}

/**
 * Implements hook_field_widget_form().
 * 
 * @todo: maybe integrate the elements of the widget into a fieldset for clearer visual presentation
 */
function simplenews_plaintext_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  
  $widget = array();

  $widget['value'] = array(
    '#type' => 'textarea',
    '#title' => $instance['label'],
    '#default_value' => isset($items[$delta]['value']) ? $items[$delta]['value'] : NULL,
    '#rows' => $instance['widget']['settings']['rows'],
    '#attributes' => array('class' => array('text-full')),
    '#prefix' => '<div id="plaintext-container">',
    '#suffix' => '</div>',
  );
  
  /* This doesn't work, had to load the js using hook_preprocess_page() (see code below)
  $jspath = drupal_get_path('module', 'simplenews_plaintext') . '/simplenews_plaintext.js';
  $form['#attached']['js'] = array($jspath); || drupal_add_js($jspath, 'file');
  */
  
  $widget['process_trigger'] = array(
    '#type' => 'submit',
    '#value' => t('Process'), // @todo maybe give the label a better text
    '#ajax' => array(
      'callback' => 'simplenews_plaintext_process_plaintext_value',
      'progress' => array(
        'type' => 'bar',
        'message' => t('Please wait while your text is being processed on the server.')
      ),
    ),
  );

  $widget = $element + $widget;

  return $widget;
}

function simplenews_plaintext_process_plaintext_value($form, $form_state) {
 
  // build a pseudonode to get all necessary field values
  $node = $form_state['node'];
  entity_form_submit_build_entity('node', $node, $form, $form_state);
  node_submit($node);
  
  // gather plaintext values from relevant fields
  /*
  // the way miro wanted it to be done, unfortunately 
  // links like 'edit' or 'delete' get rendered too this way
  $data = node_view($node, 'email_plain');
  $text = render($data);
  */
  
  // code below pulls the textdata out of $form_state directly
  $text = '';
  $field_types = array('text', 'text_long', 'text_with_summary');
  foreach($form_state['field'] as $field_name => $field) {
    // skip empty fields
    if (!isset($form_state['values'][$field_name]['und'][0]['value']) || empty($form_state['values'][$field_name]['und'][0]['value'])) continue;
    if (in_array($field['und']['field']['type'], $field_types)
        && $field['und']['instance']['widget']['type'] != 'plaintext_textarea') {
      $label = $field['und']['instance']['label'];
      if (count($form_state['values'][$field_name]['und']) > 1) {
        $text .= $label . '<br />';
        foreach($form_state['values'][$field_name]['und'] as $key => $val) {
          $text .= '<p>' . t('Value') . ' ' . ($key + 1) . '<br />' . $val['value'] . '</p>';
        }
      }
      else {
        $value = $form_state['values'][$field_name]['und'][0]['value'];
        if ($field['und']['instance']['display']['email_plain']['label'] != 'hidden') {
          $text .= '<p>' . $label . '<br />' . $value . '</p>';
        }
        else {
          $text .= '<p>' . $value  . '</p>';
        }
      }
    }
  }
  
  // convert html values of fields to plaintext
  module_load_include('inc', 'simplenews', 'includes/simplenews.mail');
  $plaintext = simplenews_html_to_text($text);

  // send the plaintext value to a client side js command
  return array(
    '#type' => 'ajax',
    '#commands' => array(
      array(
       'command' => 'replacecontent',
       'plaintext' => $plaintext,
       'trigger' => $form_state['triggering_element']['#id'],
      ),
    ),
  );
}

/*
function simplenews_plaintext_form_alter(&$form, &$form_state, $form_id) {
  dsm($form_id);
  //if ($form_id == 'article_node_form') {
    $form['#after_build'] = array('_simplenews_plaintext_load_js');
  //}
}

function _simplenews_plaintext_load_js($element) {
  $jspath = drupal_get_path('module', 'simplenews_plaintext') . '/simplenews_plaintext.js';
  drupal_add_js($jspath, 'file');
  dsm($element);
  return $element;
}
*/

/*
 * Adds the js to the process_trigger button of the widget.
 * 
 * @todo The JS should not be added on this way. Otherwise
 * the JS gets loaded on every form without plaintext widget
 * and even on every page without form. Tried to do it in the
 * simplenews_plaintext_field_widget_form() function with ['#attached']
 * attribute as well as with drupal_add_js, both cases did not work.
 * Even tried to load the JS in a corresponding form_alter hook,
 * which also did not work (see code above).
 */
function simplenews_plaintext_preprocess_page(&$variables) {
  $jspath = drupal_get_path('module', 'simplenews_plaintext') . '/simplenews_plaintext.js';
  drupal_add_js($jspath, 'file');
}
